### ISSUE TITLE
Variabelnavne

### ISSUE THREAD

**Issue by erikgahner** [njharbo/hvembliverstatsminister#1]
På nuværende tidspunkt skal jeg ind i et af de respektive Python scripts for at finde ud af, hvad de enkelte kolonner i `data.csv` viser. Det ville være godt med variabelnavne på første række i datasættet samt en beskrivelse af de enkelte variable i `README.md`.

**Comment by njharbo** [comment]
Hej, 
Godt forslag. Jeg har opdateret Readme med en beskrivelse af data.csv. Hans vil lægge variabel navnene ind i morgen. Tak!

**Comment by njharbo** [comment]
Det er fikset nu. Tak.
