### ISSUE TITLE
Opdatering af data

### ISSUE THREAD

**Issue by ekstroem** [njharbo/hvembliverstatsminister#8]
Hejsa.

Gider I smide en opdatering af data.csv på github? Mere for os, der ikke har haft "høsteren" kørende de sidste mange dage :)

**Comment by njharbo** [comment]
Done!

**Comment by ekstroem** [comment]
Mange tak. Ville lige lege med noget grafik:

http://www.biostatistics.dk/fv15.html

**Comment by njharbo** [comment]
Selv tak! Det ser fedt ud. Tak!
